### ISSUE TITLE
과제 제출명 관련해서 질문 드립니다.

### ISSUE THREAD

**Issue by beomso0** [hcid-courses/datajournalism-2018#13]
언론정보학과 2017-11009 김범수입니다.
지금 과제 제출 폴더명을 다시 검토하고 있는데, Assignment 2-2가 week3 exercise(100 little monkey가 포함된)을 지칭하는 것인지 궁금합니다. 
감사합니다.

**Comment by drater05** [comment]
네 그 과제가 그 과제 맞구요

폴더명은 Assignment_2-2 입니다

참고 : https://hcid-courses.github.io/TA/notice/naming_assignments.html

**Comment by yuyupopo** [comment]
`A1-2017-00000-YourName.ipynb` 파일은 어떤 과제에 해당하는 것인가요?

**Comment by drater05** [comment]
@yuyupopo 앗 그건 실수입니다.. ㅎㅎ

과제 1은 codecademy 캡처 이미지 파일 혹은 면제 요청 링크로 채점되었습니다

공지도 수정했어요!
