### ISSUE TITLE
Week12 Lab 코드에서 json 파일을 불러올 때 오류가 발생합니다.

### ISSUE THREAD

**Issue by beomso0** [hcid-courses/datajournalism-2018#17]
### 실행 환경

- Windows10 + 64bit + 8GB / Python **3.7.0** / Jupyter Notebook

### 코드

```python
import json

json_data = []
with open("tweet_stream.json") as file:
    data = file.readlines()
    for d in data:
        json_data.append(json.loads(d))
```

### 설명

Week 12 lab 코드를 그대로 실행한 것입니다.

### 에러 메시지

```
JSONDecodeError                           Traceback (most recent call last)
<ipython-input-69-170fc6c10810> in <module>()
      5     data = file.read()
      6     for d in data:
----> 7         json_data.append(json.loads(d))
      8 

c:\users\bumso\appdata\local\programs\python\python37\lib\json\__init__.py in loads(s, encoding, cls, object_hook, parse_float, parse_int, parse_constant, object_pairs_hook, **kw)
    346             parse_int is None and parse_float is None and
    347             parse_constant is None and object_pairs_hook is None and not kw):
--> 348         return _default_decoder.decode(s)
    349     if cls is None:
    350         cls = JSONDecoder

c:\users\bumso\appdata\local\programs\python\python37\lib\json\decoder.py in decode(self, s, _w)
    335 



    336         """
--> 337         obj, end = self.raw_decode(s, idx=_w(s, 0).end())
    338         end = _w(s, end).end()
    339         if end != len(s):

c:\users\bumso\appdata\local\programs\python\python37\lib\json\decoder.py in raw_decode(self, s, idx)
    351         """
    352         try:
--> 353             obj, end = self.scan_once(s, idx)
    354         except StopIteration as err:
    355             raise JSONDecodeError("Expecting value", s, err.value) from None

JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
```

**Comment by drater05** [comment]
해당 error는 **Windows system의 기본 <u>줄바꿈 문자</u>가 예제 코드 테스트 환경인 mac os와 달라서** 일어난 문제입니다. 수업 중에도 몇 학생이 그랬었는데 자세히 답변을 못했네요

사실 수업시간의 코드 뿐만 아니라 프로그래밍과 데이터 분석 전반에서 활용되는 대부분의 프로그램/코드는 linux/mac과 유사한 환경에서 개발되고 테스트되기 때문에 windows에서 가끔 사소한 오류가 나는 것은 피할 수 없습니다...

수업에서 설명되었던 encoding(CP949 / UTF-n) 문제처럼 그냥 어쩔 수 없는 문제이니 windows를 사용하는 학생들이 이런 몇가지 흔한 문제들에 빨리 익숙해지고 스스로 해결할 수 있도록 도와드릴 수밖에 없을 것 같아요

아무튼 이 문제도 실제 해결방법만 보면 간단하긴 한데, 앞으로 수도 없이 비슷한 문제가 발생할 수 있기 때문에 좀 자세히 설명합니다. 아직 기초가 부족하기 때문에 에러가 어디서 발생하는지, 왜 발생하는지를 알아야 어떻게 해결하는지를 알 수 있고 앞으로 유사한 경우에도 잘 대처할 수 있을것 같아요



우선 [줄바꿈 문자-wiki](https://ko.wikipedia.org/wiki/%EC%83%88%EC%A4%84_%EB%AC%B8%EC%9E%90)(linebreak; 예제 코드에서의 `'\n'` 등)는 소위 말하는 '엔터'로 스페이스나 탭처럼 공백문자의 일종이며 컴퓨터에서는 `'a'`, `'1'` 처럼 문자의 일종으로 취급되지만 그 유형이 시스템에 따라 하나가 아니라 여러가지입니다.

위키에도 나와있듯 역사적인 배경 때문에 현재 Windows에서는 기본 줄바꿈 문자로 CR+LF(`'\r\n'`)을 사용하며 DOS에서는 CR(`'\r'`)을 사용했고 mac이나 linux에서는 LF(`'\n'`)을 사용하고 있습니다.

그런데 다양한 OS에서 쓰이는 python의 경우 아직 다양한 환경에서의 공통적인 줄바꿈(linebreak) 처리가 아주 깔끔하지는 않아서 라이브러리(모듈)마다 처리 방식이 조금씩 달라요.... 한참 전에 python 내부 표준안이 제시되었지만 조금씩 맞춰나가고 있어요. 

결국은 CR(`'\r'`)과 LF(`'\n'`), CR+LF(`'\r\n'`)가 혼합되어있는 문자열들을 어떻게 합치거나 나눌지 논리가 시스템 환경 및 개별 함수마다 좀 다를 수 있다고 생각하면 됩니다.

**이러한 이유로 windows 환경에서 python을 사용할 때 linebreak character 때문에 가끔 생각하지 못한 일들이 일어날 수 있으니, 내가 만들지 않은(파일에서 읽어왔거나 api에서 받은) string을 line 단위로 처리하여 읽거나 쓰려고 할 때는 개행문자를 의식하고 사용하시고 문제가 생기면 확인을 해보는 것이 좋습니다.**

구체적으로 질문에서의 에러에 관해 설명하면, 우선 Week12 예제에서 사용한 `tweepy` 모듈은 내부적으로 시스템의 기본 linebreak(`os.linesep`)을 사용합니다. 

따라서 예제에서 정의된 MyListener class를 활용할 때

```python
class MyListener(tweepy.StreamListener):
    def on_data(self, data):
        with open('tweet_stream.json', 'a') as file:
            file.write(data)
            print(data)
            ...
```

위의 `on_data()` 함수에서 받는 parameter인 `data`라는 json string에는 linebreak이 하나 붙어서 오게 되는데, `data`의 값이 linux/mac에서는 `'{...}\n'`이고 windows에서는 `'{...}\r\n'`으로 다르게 전달됩니다. 
(위 코드에서 `print(data)` 대신 `print(repr(data))`를 해보고 출력을 읽으면 알수 있어요)



이러한 `data` string이 `file.write`함수를 통해 파일에 기록될 때는 `write` 함수 내부에서 linebreak에 관해 한번 처리를 하는데, windows python에서는 **별다른 설정을 하지 않으면** CR은 무시하고, <u>LF를 시스템 기본 linebreak (windows에서는 CR+LF)으로 바꿔</u>서 저장합니다. [open() docs 참고](https://docs.python.org/3/library/functions.html#open)
(`'{...}\r\n'` => `'{...}\r\r\n'`)

결국 Windows에서 MyListner를 이용하여 data를 여러번 받아서 저장하려고 하면 linux/mac에서와 달리 `'tweet_stream.json'` 파일에는 
`'{...}\r\r\n{...}\r\r\n{...}\r\r\n'` 처럼 이상한 줄바꿈이 붙은 string이 저장되는 문제가 생깁니다.  보통 하나의 데이터 파일 안에서는 한 종류의 linebreak 문자를 사용하는 것이 관습이기 때문에 CR과 CRLF가 혼용된 파일은 이상한 파일입니다.



그래서 이렇게 저장된 `'tweet_stream.json'` 파일을 아래의 코드에서 다시 읽어들일 때 혼란이 생깁니다.

```python
json_data = []
with open("tweet_stream.json") as file:
    data = file.readlines()
    for d in data:
        json_data.append(json.loads(d))
```

 `file.readlines()`는 읽어들인 파일을  line 단위로 알아서 끊어 string list를 리턴하는 함수로, 기본 설정으로도 CR+LF나 LF 등의 줄바꿈 문자가 섞여있을때 알아서 잘 분리하여 쪼개고 모든 줄바꿈 문자를 LF로 바꿔주는 알고리즘이만, 그래서  `'\r\r\n'` 를 읽을 때  CR(`'\r'`)과 CR+LF(`'\r\n'`)이 붙어 있는 것으로 처리하여, 정상적인 json string이 없이 **비어있는 line**(`'\n'`)이 사이사이에 들어있는 list를 리턴하게 됩니다.

input file string : `'{...}\r\r\n{...}\r\r\n{...}\r\r\n'` 

readlines() return : `data = ['{...}\n', '\n', '{...}\n', '\n', '{...}\n', '\n']`

이런 리스트 `data`에 대해 for 문 안에서 각각의 요소 `d`를 `json.loads(d)`를 이용하여 json으로 읽으려고 하면, 

정상적인 json string을 처리할 때는 문제가 없지만(e.g., `json.loads('{}\n')`) 

빈 라인을 처리할 경우 (`json.loads('\n')`) 질문에서의 에러인 `JSONDecodeError`가 raise됩니다.

json에서 empty line을 decode하지 못하는 이유는 그냥 처음부터 그렇게 <u>약속되어있지 않기</u> 때문이에요. json의 구조에 대한 설명은 많으니 한번 대충 읽어보는것도 좋습니다. [국문 설명](https://www.json.org/json-ko.html), [공식 문서](https://tools.ietf.org/html/rfc7159)





이런 내용을 어느 정도 이해하고 나면 windows, python3, newline separator 등으로 구글링하면 비슷한 사례가 많고 오류 처리 방법도 다양하니 편한 방법으로 해결하면 됩니다.



간단한 해결방법 하나는 MyListener class 내부에서 `tweet_stream.json`  file을 열 때 `newline` keyword를 LF(`'\n'`)로 명시하면 windows python의 `open()`에서 발생하는 LF -> CRLF의 vicious translation을 피할 수 있습니다.  [다시 open() docs 참고](https://docs.python.org/3/library/functions.html#open)

```python
class MyListener(tweepy.StreamListener):
    def on_data(self, data):
        with open('tweet_stream.json', 'a', newline='\n') as file:
            file.write(data)
            print(data)
            ...
```

(in line 3;)

- original :  `open('tweet_stream.json', 'a')`

-  edited : `open('tweet_stream.json', 'a', newline='\n')`

**Comment by beomso0** [comment]
상세한 답변 정말 감사드립니다. 
 
답변 주신 내용 바탕으로 다시 시도해보도록 하겠습니다. 감사합니다!
 
김범수 드림.

**Comment by wltjd54** [comment]
죄송한데 알려주신 방법으로 해도 잘 해결이 되지 않습니다..

**Comment by drater05** [comment]
@wltjd54 이미 만들어진 `tweet_stream.json` 삭제 후 다시 해도 안되나요 ?

**Comment by wltjd54** [comment]
아 삭제하고 다시 시도했더니 잘 됩니다. 감사합니다!

**Comment by drater05** [comment]
네 file write 할때 `open('tweet_stream.json', 'a', newline='\n')`에서 'a' 옵션으로 append 하면 기존 파일에 잘못된 부분이 그대로 남아있어서 같은 오류가 생겼을 거에요~
