### ISSUE TITLE
크롤링 과정에서 오류가 납니다

### ISSUE THREAD

**Issue by tomboy2007** [hcid-courses/datajournalism-2018#20]
### 실행 환경

- Windows10 + 32bit + 8GB / Python **3.7** / Jupyter Notebook 

### 코드

*코드 파일 전체를 올리지 말고, 에러가 일어난 라인 및 의존성이 있는 부분(import package, 사용한 변수의 선언 등)만 올려주세요*  

```python
# put your code segment here..

import urllib.request
from urllib import parse
import json

class Crawler(object):

    def __init__(self, city="Jeju", region="성산읍", courseId="164", tm="2018113001):
        self.city = city      
        self.county = region
        self.courseId = courseId
        self.tm = tm
    
    def forecast_fetch(self, courseId="164", tm="2018113001"):
        self.courseId = courseId
        self.tm = tm

        app_key = ""
        loc = self.courseId
        time = self.tm
        url = "http://newsky2.kma.go.kr/service/TourSpotInfoService/SpotIdxData?CURRENT_DATE={}&HOUR=24&COURSE_ID={}&serviceKey={}&_returnType=json".format(time, loc, app_key)
        
        with urllib.request.urlopen(url) as response:
            self.forecast_data = json.loads(response.read().decode("utf-8"))

        return self.forecast_data
print(forecast_data)
```

### 설명

공공데이터포털에서 '관광코스 기상정보 API'를 가져와서 크롤링하는데 제가 원하는 시간이랑 course Id, app key를 넣어도 안돼요...

### 에러 메시지

```
# copy & paste your error message here..

NameError                                 Traceback (most recent call last)
<ipython-input-26-a4ca3c4e96bd> in <module>
     46 
     47         return self.forecast_data
---> 48 print(forecast_data)

NameError: name 'forecast_data' is not defined
```

**Comment by yuyupopo** [comment]
I believe you have a typo at the last line
`print(self.forecast_data)`

**Comment by drater05** [comment]
- (개인용 api의 app key를 공개 포스트에 올리면 유출될 우려가 있어 본문 수정했어요~)

코드에서 오타 수정할 것
`def __init__(self, city="Jeju", region="성산읍", courseId="164", tm="2018113001):`
`def __init__(self, city="Jeju", region="성산읍", courseId="164", tm="2018113001"):`
(`"`빠져있는 것 수정)


먼저 공공데이터포털에서 제공하는 '관광코스 기상정보 API'는 xml 형태로만 제공되는 것 같아요. 모든 api가 다 `returnType=json`을 넣는다고 json 데이터를 돌려주는건 아니니, 항상 api 설명서를 확인하세요.

물론 json 말고 xml 데이터도 간단하게 처리할 수 있구요
python의 `xmltodict`같은 라이브러리를 사용하면 dictionary로 바로 파싱해서 읽을 수 있어요. [참고링크](https://docs.python-guide.org/scenarios/xml/)

`pip install xmltodict`로 패키지를 설치해주고 코드에서 패키지를 불러와준 후 (`import xmltodict`) 본문 코드의 `json.loads(...)` 부분을 `xmltodict.parse(...)`로 바꾸면 될거에요


원글 내용에서 실제 코드에서 난 에러를 보면 변수의 scope를 무시하고 print해서 문제가 생긴 것 같은데, 수업에서 파이썬 진도를 너무 빨리 나가서 파이썬 문법이나 class 사용이 아직 좀 어색한 것 같아요ㅜ
암튼 위의 xml 부분이 모두 잘 수정되었다면, 마지막 줄의 print문 대신
```
crawler = Crawler()
sample_forecast_data = crawler.forecast_fetch()
print(sample_forecast_data)
```
이런 식으로 하면 결과가 나올 거에요

잘 안되면 추가 댓글 달아주세요~

**Comment by tomboy2007** [comment]
감사합니다! app key 보호도 감사드려요ㅎㅎㅎ
알려주신 대로 했더니 해결됐어요!
