### ISSUE TITLE
'<' 에러

### ISSUE THREAD

**Issue by jiwonleem** [hcid-courses/datajournalism-2018#24]
### 실행 환경

Windows10 + 64bit + 8GB / Python **3.6.5** / Jupyter Notebook 

### 코드
```python
rush_hour_usage_time_place = data[(rush_hour_seven_eight['place'].value_counts().nlargest(10)) & (data.time  < 20) ]
```

### 설명

다른 index들  data.hour  은 이렇게 했을 때 돌아가는데, 왜 data.time만 안되는지 궁금합니다.  
data.time은 14.0이런 float 형식으로 되있긴 한데, float으로 바꿔놓은 경우에도 되지는 않아서 그게 문제인게 아닌거 같아서 질문합니다!

### 에러 메시지

```
# D:\lib\site-packages\pandas\core\indexes\base.py:3772: RuntimeWarning: '<' not supported between instances of 'str' and 'int', sort order is undefined for incomparable objects
  return this.join(other, how=how, return_indexers=return_indexers)
D:\lib\site-packages\ipykernel_launcher.py:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index
```

**Comment by drater05** [comment]
질문만 봐서는 data가 어떤 내용의 테이블인지 몰라서 정확히 답을 못하겠네요

time column dtype이 float가 맞나요? 

에러 메시지를 보면 data.time이 str일거 같아요

`data.dtypes` 결과를 확인해보세요
