### ISSUE TITLE
Week 5 - Solution 실습 6의 코드가 잘 이해가 되지 않습니다

### ISSUE THREAD

**Issue by wltjd54** [hcid-courses/datajournalism-2018#5]
### 실행 환경

- Windows10 + 64bit + 8GB / Python **3.7.0** / Jupyter Notebook

### 코드

```python
# put your code segment here..
paid_students = {}

for enrollment in non_udacity_enrollments:
    if not enrollment['is_canceled'] or enrollment['days_to_cancel'] > 7:
        account_key = enrollment['account_key']
        enrollment_date = enrollment['join_date']
        
        # paid_students[account_key] = enrollment_date -> 이렇게 해도 됨. 하지만 아래에서 좀더 경우의 수를 체크.
        
        # account_key 가 paid_students에 이미 들어있지 않거나 enrollment_date가 이미 존재하는 날짜 보다 최근일 경우만 추가
        if account_key not in paid_students or enrollment_date > paid_students[account_key]: 
            paid_students[account_key] = enrollment_date

print(len(paid_students))

```

### 설명

```python
        if account_key not in paid_students or enrollment_date > paid_students[account_key]: 
            paid_students[account_key] = enrollment_date
```

여기에서 enrollment_date>paid_students[account_key] 부분에서 우선 이 코드가 무엇을 의미하는지(혹은 어떤 이유로 필요한지), 그리고 현재 paid_student[account_key]에는 아무런 value값도 assign되어 있지 않은데 비교를 할 수 있는 것인지 궁금합니다.

**Comment by drater05** [comment]
안녕하세요. 수업조교 김준석입니다.

(질문 원글에서 작성자가 추가한 부분은 남겨두고 템플릿의 예시 부분을 삭제하여 조금 수정했습니다.)

질문 주신 내용은 위 코드에서 `non_udacity_enrollments` 라는 list의 내용을 실제로 살펴보면 더 쉽게 이해할 수 있을 것 같습니다.

`non_udacity_enrollments` list는 복수의 OrderedDict를 담고 있으며 'account_key'가 unique하지 않고, 'join_date'가 unsorted된 list입니다.

그러니까 어떤 학생, 예를 들어 429번이 14년 11월에 등록했다가 몇달 후 취소하고, 다시 등록한 경우 이를 연속된 한 번으로 세지 않고 각각의 경우로 나누어 list에 저장되어 있는 것을 확인할 수 있습니다.

![image](https://user-images.githubusercontent.com/7570803/46332506-b53e1800-c657-11e8-8dbe-ffb81308ad2d.png)

또한 그 순서도 일정하지 않습니다. 시간상 나중에 등록된 데이터가 list에서 나중에 있지 않고 앞에 있는 경우도 있습니다.

![image](https://user-images.githubusercontent.com/7570803/46333292-d6ecce80-c65a-11e8-9cff-dc01b63d8261.png)

_따라서 단순히 paid student의 숫자만을 계산하자면_ 교수님 코드의 comment(`# paid_students[account_key] = enrollment_date -> 이렇게 해도 됨. 하지만 아래에서 좀더 경우의 수를 체크.`) 처럼 저 부분에서 바로 `paid_students` dictionary에 해당 account_key를 저장해도 별 문제는 없습니다.

하지만 `paid_students`에 조금 더 의미있는 정보, 예를 들면 **실제로 등록한 학생들의 account_key와 각각의 가장 최근 등록 날짜**를 저장하고 싶다면 Solution에 제시된 코드처럼 더 구체적인 경우의 수를 나누어 확인하면 좋습니다.

이러한 맥락에서 질문에 답을 드리면 예를 들어 non_udacity_enrollments list에는 이런 데이터가 포함되어 있습니다. (불필요한 key-value는 생략)

```python
[
...,
 OrderedDict([
              ('account_key', 1121),
              ('join_date', datetime.datetime(2014, 12, 29, 0, 0)),
              ('days_to_cancel', 14),
              ('is_canceled', True)]),
 OrderedDict([
              ('account_key', 1121),
              ('join_date', datetime.datetime(2014, 11, 11, 0, 0)),
              ('days_to_cancel', 48),
              ('is_canceled', True)]),
...,
]
```

for loop를 돌다가 위의 예에서 account_key가 1121인 _**첫번째**_ enrollment ('join_date', datetime.datetime(2014, 12, 29, 0, 0))를 처리하는 경우를 살펴보면 다음과 같습니다.

 우선 첫번째 if절 `if not enrollment['is_canceled'] or enrollment['days_to_cancel'] > 7:`에 해당되어(`enrollment['days_to_cancel'] = 14 > 7 : True`) 등록한 학생으로 간주하고

그 밑의 if문에서는 `account_key not in paid_students` 조건에 해당합니다. **(python에서 두 조건이 or로 연합된 경우 앞의 조건이 True이면 뒤의 조건은 계산하지 않습니다.)**

이때 `paid_studens`는 처음으로 1121의 key를 추가하여 `{..., 1121: datetime.datetime(2014, 12, 29, 0, 0)}`의 내용이 됩니다. <*>

이후 account_key가 1121인 _**두번째**_ enrollment ('join_date', datetime.datetime(2014, 11, 11, 0, 0))를 처리할때는 역시 첫번째 if절을 통과하지만 (`enrollment['days_to_cancel'] = 48 > 7 ; True`)

그 밑의 if문에서는 `account_key`인 1121이 이미 `paid_studens` dictionary에 존재하는 key이기 때문에(`account_key not in paid_students ; False`) 두 번째 조건 `enrollment_date > paid_students[account_key]`을 평가합니다.

이때 (1) `enrollment_date`는 `datetime.datetime(2014, 11, 11, 0, 0)`이고,
(2) `account_key`는 1121이므로 이 시점에서 `paid_students[account_key]`는 `datetime.datetime(2014, 12, 29, 0, 0)`의 값이므로(위의 <*> 참고)

결국 조건문 `enrollment_date > paid_students[account_key]`은 `datetime.datetime(2014, 11, 11, 0, 0) > datetime.datetime(2014, 12, 29, 0, 0)` : `False`로 계산됩니다.

위 경우에서는 loop에서 현재 보고 있는 enrollment 데이터의 join_date가 이전에 저장했던 동일 키의 join_date값보다 작기 때문에 `paid_studens`의 값을 업데이트하지 않습니다.



결론은 위에 예로 들었던 경우처럼 `non_udacity_enrollments` 안에 account_key의 중복이 있을 경우, 그리고 동시에 중복된 account_key에 대해 paid enrollment가 복수인 경우에 최신 등록일만 남기고 싶다면 Solution처럼 추가 조건을 넣을 수 있습니다. 

첫 질문이라 약간 자세하게 썼는데, 답변이 부족하거나 추가 질문이 있으면 커멘트 해주세요.

python 기본 문법과 데이터 구조에 완전히 익숙해지기 전까지는 이해가 가지 않는 부분들에 대해 중간중간에 `print()` 등을 활용하여 실제로 각 시점에서 값이 무엇이고 어떻게 바뀌고 있는지를 확인하면서 코딩해보는 것도 좋아요.
