### ISSUE TITLE
Jupyter notebook 에러가 발생한 것 같습니다.

### ISSUE THREAD

**Issue by lshzzz** [hcid-courses/datajournalism-2018#6]
### 실행 환경

- Windows10 + 64bit + 8GB / Python 3.7.0 / Jupyter Notebook 

### 문제 상황

Jupyter notebook 으로 week5 내용을 복기하던 중 실습 3-2 코드를 실행하자 갑자기 다음과 같은 에러 메시지가 나타났습니다. crashing을 막기 위해 서버에서 뭔가 제한을 건 것 같은데 해결이 되지 않습니다.

### 에러 메시지

```
IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)


```

### 스크린샷

![default](https://user-images.githubusercontent.com/43499944/46552933-252df600-c917-11e8-8270-0342620e7f0f.png)

**Comment by drater05** [comment]
kernel restart 해도 같은 문제가 발생하나요?

혹은 터미널에서 jupyter notebook을 종료시켰다가 다시 실행해도 계속 같은 오류가 생기나요?

**Comment by lshzzz** [comment]
> kernel restart 해도 같은 문제가 발생하나요?
> 
> 혹은 터미널에서 jupyter notebook을 종료시켰다가 다시 실행해도 계속 같은 오류가 생기나요?

**Comment by lshzzz** [comment]
> kernel restart 해도 같은 문제가 발생하나요?
> 
> 혹은 터미널에서 jupyter notebook을 종료시켰다가 다시 실행해도 계속 같은 오류가 생기나요?

둘 다 해봤는데 계속 같은 오류가 나옵니다. ㅜㅜ

**Comment by drater05** [comment]
터미널에서 jupyter 실행할 때
```
jupyter notebook --NotebookApp.iopub_data_rate_limit=10000000
```
이렇게 실행해도 안되나요?

**Comment by lshzzz** [comment]
이렇게 실행하니 해당 코드 실행시 아예 jupyter가 멈춰버리네요.

**Comment by drater05** [comment]
아. 스크린샷 자세히 보고 이해했어요.
해당 이슈는 원래 output 크기가 너무 클때 생기는 문제인데 겨우 숫자 세개 뽑을때 왜 그런 문제가 생기나 했더니ㅜ

스크린샷 코드에서는 `unique_students` 함수의 결과들이 아니라 `daily_engagement`, `project_submissions`를 모두 print 하느라 너무 출력할 line이 많아서 그런 문제가 있었던 것 같아요.

solution code와 비교:
```
# 스크린샷에서 실행된 코드
print(unique_students(enrollments, 'account_key'))
print(daily_engagement, 'acct')
print(project_submissions, 'account_key')

# Solution 코드
print(unique_students(enrollments, 'account_key'))
print(unique_students(daily_engagement, 'acct'))
print(unique_students(project_submissions, 'account_key'))
```

**Comment by lshzzz** [comment]
제가 바보짓을 하고 있었네요... 도와주셔서 감사합니다!
