### ISSUE TITLE
datafram 객체에서 특정 index 사용시 오류

### ISSUE THREAD

**Issue by jiwonleem** [hcid-courses/datajournalism-2018#9]
### 실행 환경
-Windows10 + 64bit + 8GB / Python **3.6.5** / Jupyter Notebook 

### 코드

*코드 파일 전체를 올리지 말고, 에러가 일어난 라인 및 의존성이 있는 부분(import package, 사용한 변수의 선언 등)만 올려주세요*  

```python
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from pandas import DataFrame


data = pd.read_excel('titanic3.xls')
data.index = data.name
data = data.drop('name', axis=1)

data_q1 = data.loc[['sex', 'age', 'survived']]
data_q1

```

### 설명

자료에서의  column 들이 많아서 1번문제에서는 sex, survived, name, age만 사용하려 합니다.  새로운 Dataframe 객체를 만들려고 합니다.

### 에러 메시지

"None of [['sex', 'age', 'survived']] are in the [index]"

이런식으로 오류가 계속되는데 혹시 파일을 csv로 읽지 않아서 그런건가 했는데, 파일자체가 xls이니 어차피 csv로 읽히지는 않더라구요.  
datafram 의 loc 속성을 이용해서 특정 인덱스의 데이터만 가져오고 싶은것인데 왜 안되는 것인지 궁금합니다. 
혹시나 하여 from pandas import DataFrame 을 해본 것인데 변화가 없네요.
```

**Comment by monot** [comment]
data.column 을 실행하고 그 결과값을 올려봐줄래요?

**Comment by jiwonleem** [comment]
'DataFrame' object has no attribute 'column' 

이렇게 에러가 나옵니다!

**Comment by monot** [comment]
미안해요.  `data.columns`

**Comment by jiwonleem** [comment]
Index(['pclass', 'survived', 'sex', 'age', 'sibsp', 'parch', 'ticket', 'fare',
       'cabin', 'embarked', 'boat', 'body', 'home.dest'],
      dtype='object')  

이렇게 나옵니다! 
그리고 하나 궁금한게, 만약 csv로 파일을 읽어서 하려면 엑셀파일을 csv로 변환해서 해야하는건가요? dataframe이 csv랑만 호환이 되는건지 궁금해서요

**Comment by monot** [comment]
지금 현재 엑셀을 읽어 dataframe 을 만듭겁니다. 다시 보니 data.loc 를 했었네요. 현재, index 는 name 하나만 지정해 뒀구요.
그러니까 loc는 인덱스 name 만 쓸 수 있습니다. data.loc[['sex', 'age', 'survived']] 는 안됩니다.
다음과 같이 해보세요.
`data[['sex', 'age', 'survived']] `

**Comment by jiwonleem** [comment]
아 네! 그렇게하니 해결이 되었네요 ㅎ
근데 
data.index = data.name 를 생략했을 때도 

"None of [['sex', 'age', 'survived']] are in the [index]"
다음과 같은 문제가 나왔어서, 이때에는 어떤 점이 잘못된건지 궁금합니다.

**Comment by monot** [comment]
지금 계속 이야기 하는 건 column 의 이름이고, index 는 row 를 의미해요. 그러니 data.index 안했을 때도 sex, age, survived 는 index 가 아니에요.

**Comment by jiwonleem** [comment]
네 알겠습니다!
